### ISSUE TITLE
Is it ready for production ?

### ISSUE THREAD

**Issue by reni11111** [masahirompp/aws-cdk-webpack-lambda-function#1]
I see it's a wrapper of lambda constructor, but is anything missing ?

**Comment by masahirompp** [comment]
sorry to reply late.
I use it in production, and there are no particular problems.

**Comment by reni11111** [comment]
I'm using it too, it seems perfect (Y).
The only problem I found till now is that it doesn't support sugar syntax  es2020 '?'
example       var a={}         a.name?.value
Do you have any webpack config for it (not really a webpack guy)

**Comment by masahirompp** [comment]
if using ts-loader(transpile by typescript), es2019 under supported.
see also https://github.com/microsoft/TypeScript-wiki/blob/master/Node-Target-Mapping.md

you can transpile es2020(typescript) to es2019(javascript) using babel-loader.

example

```js
module.exports = {
  mode: "production", // production or development
  target: "node",
  externals: [/^aws-sdk(\/.+)?$/], // important!!!
  devtool: "source-map", // if needed
  optimization: { minimize: false }, // if needed
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: {
          loader: "bable-loader",
          options: {
            babelrc: false,
            sourceType: "unambiguous",
            presets: [
              [
                "@babel/preset-env",
                {
                  modules: false,
                  useBuiltIns: "usage",
                  targets: { node: 12 }, // Node.js version
                },
              ],
              "@babel/preset-typescript",
            ],
            plugins: ["@babel/plugin-proposal-optional-chaining"],
          },
        },
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [".js", ".ts"],
  },
};
```

thanks

**Comment by reni11111** [comment]
I am not using typescript (vanilla javascript here), will the same configuration work?

**Comment by masahirompp** [comment]
@reni11111 sorry, I'm not familiar with vanilla.
