### ISSUE TITLE
Support for CDK 2

### ISSUE THREAD

**Issue by muhamadto** [masahirompp/aws-cdk-webpack-lambda-function#19]
Thanks for this library, it's pretty handy. Any chance you can dedicate sometime to support CDK v2

**Comment by muhamadto** [comment]
Here is a PR for this issue https://github.com/masahirompp/aws-cdk-webpack-lambda-function/pull/20. Please review.

**Comment by masahirompp** [comment]
@muhamadto Thanks for your PR. I've merged the pull requests and released them. please use aws-cdk-webpack-lambda-function@1.0.0

**Comment by muhamadto** [comment]
@masahirompp no, thank you! I'm using your library for building a [template for CRUD api](https://github.com/muhamadto/cdk-crud-api-template) using lambda and apigateway. Your work is so helpful.
