### ISSUE TITLE
Update cdk dependencies

### ISSUE THREAD

**Issue by reni11111** [masahirompp/aws-cdk-webpack-lambda-function#3]
At package.json there are some old versions of aws-cdk
```
    "@aws-cdk/aws-lambda": "^1.33.1",
    "@aws-cdk/core": "^1.33.1",
```
Can you upgrade to the latest 1.47.0 ?
I can make a pull request too, but how can I know if version change breaks something? (any test?)

**Comment by masahirompp** [comment]
@reni11111 I upgrade to the latest 1.66.0. I also wrote a test.
